### ISSUE TITLE
New SSO for Garmin breaks script

### ISSUE THREAD

**Issue by wederbrand** [kjkjava/garmin-connect-export#2]
Garmin has re done there authentication to use a SSO instead. This breaks the script.

I've used parts of your code in my own project https://github.com/wederbrand/workout-exchange so that is also broken.

We should collaborate on a solution if we both try to fix it.

**Comment by kjkjava** [comment]
@wederbrand, thanks for sharing your solution! I just fixed this script, though yours looks a bit more flexible if it still works.
