### ISSUE TITLE
Exception: Failed. Got an unexpected HTTP error (410)

### ISSUE THREAD

**Issue by jaybe1966** [kjkjava/garmin-connect-export#25]
When I try to download my Garmin Workouts, the last activity ist listed, then the Download of the file is tried and the I receive the following exception:

```
Traceback (most recent call last):
  File "./gcexport.py", line 231, in <module>
    raise Exception('Failed. Got an unexpected HTTP error (' + str(e.code) + ').')
Exception: Failed. Got an unexpected HTTP error (410).
```

**Comment by hadadidror2** [comment]
I'm getting the same error. How do you fix this?

**Comment by jaybe1966** [comment]
No, haven't fixed it. Hope to get help here.

**Comment by moderation** [comment]
@jaybe1966 and @hadadidror2, HTTP status 410 means the endpoint you are requesting is gone.  The script hasn't been updated in a long time and the endpoints listed at https://github.com/kjkjava/garmin-connect-export/blob/master/gcexport.py#L90-L96 are out of date. See related discussion at https://github.com/kjkjava/garmin-connect-export/issues/18. In my fork you can see the updated URLs that do work - https://github.com/moderation/garmin-connect-export/blob/master/gcexport.py#L135-L141

**Comment by jaybe1966** [comment]
Thanks, this problem now is fixed but I receive another one. Will open a new issue for that.
