### ISSUE TITLE
TypeError: cannot concatenate 'str' and 'int' objects

### ISSUE THREAD

**Issue by jaybe1966** [kjkjava/garmin-connect-export#26]
When downloading Workouts, the program reports an Exception:

```
        Downloading file...
Traceback (most recent call last):
  File "garmin-connect-export_moderation/gcexport.py", line 357, in <module>
    data = http_req(download_url)
  File "garmin-connect-export_moderation/gcexport.py", line 86, in http_req
    raise Exception('Bad return code (' + response.getcode() + ') for: ' + url)
TypeError: cannot concatenate 'str' and 'int' objects
```

**Comment by moderation** [comment]
You reported the issue here but I think you are using my fork. This error _should_ be fixed with this commit https://github.com/moderation/garmin-connect-export/commit/64c0ff1e4d0589423548569c64485f88f5c51840

**Comment by jaybe1966** [comment]
Yes, the TypeError is now fixed.

**Comment by jaybe1966** [comment]
I'm using your fork https://github.com/moderation/garmin-connect-export and get another error now, but can't create an issue on the site of your fork.

**Comment by moderation** [comment]
I've enabled issues on the repo now - https://github.com/moderation/garmin-connect-export/issues
