### ISSUE TITLE
Crashes with 404 error

### ISSUE THREAD

**Issue by stevemcqueen** [kjkjava/garmin-connect-export#37]
Can only get through a couple workout files without seeing the following error. Restarting script will get me past the one file, but it crashed again a couple files later

(using https://github.com/moderation/garmin-connect-export/blob/master/gcexport.py)

Garmin Connect activity: [1953986132] Schenectady Running
	Thu, Aug 31, 2017 7:57 AM, 00:17:43, 1.95 Miles
verboseprint
https://connect.garmin.com/modern/proxy/download-service/export/gpx/activity/1953986132?full=true
	Downloading file... http exception
404
Traceback (most recent call last):
  File "gcexport.py", line 394, in <module>
    raise Exception('Failed. Got an unexpected HTTP error (' + str(e.code) + ').')
Exception: Failed. Got an unexpected HTTP error (404).

**Comment by moderation** [comment]
@stevemcqueen this repository is dead and the original author isn't responding to issues or merging PRs. Can you repost this issue over at my [fork](https://github.com/moderation/garmin-connect-export) and repost the error using the latest master code?

**Comment by stevemcqueen** [comment]
I tried it again with a fresh copy of your program and I didn't get the error. If it reoccurs I'll report it at your fork
