### ISSUE TITLE
"HTTP error 402: payment required" 

### ISSUE THREAD

**Issue by magalive1991** [kjkjava/garmin-connect-export#49]
Hello, I am using this code for a while now and it's been working great, thanks a lot ! 
But from today I get this error message when running it : "HTTP error 402: payment required" 
It is happening when trying to access the activity list at url :
https://connect.garmin.com/modern/proxy/activitylist-service/activities/search/activities?start=0&limit=1
Can you help ?
Thank you,
Magali

**Comment by embear** [comment]
I also use this great script on a regular basis and since today I'm facing the same problem.

**Comment by embear** [comment]
You can also use a recent and actively developed fork of the script. https://github.com/cpollet/garmin-connect-export includes a hot-fix for the HTTP error. But for the future the fork https://github.com/johannesh83/garmin-connect-export might be a better choice.
